python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A1.PGDs2i7e8_B9.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A2.PGDs2i7e8_B8.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A3.PGDs2i7e8_B7.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A4.PGDs2i7e8_B6.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A5.PGDs2i7e8_B5.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A6.PGDs2i7e8_B4.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A7.PGDs2i7e8_B3.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A8.PGDs2i7e8_B2.none.yaml
python -m tool.train --config config/imagenet200/Linf_weightedincreasing2to10_esat_pgd7_decreasing_entropy/resnet50_A9.PGDs2i7e8_B1.none.yaml
