manual_seed: 123

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

training_data:
  type: 'Caltech256'
  kwargs:
    root: '~/data/caltech256/256_ObjectCategories'
    split: 'train'
  transformation:
    crop:
      type: 'torchvision.transforms.RandomResizedCrop'
      args: [224]  #size, padding
    flip: 
      type: 'torchvision.transforms.RandomHorizontalFlip'
    colorjitter:
      type: 'torchvision.transforms.ColorJitter'
      args: [.1, .1, .1]
    rotation:
      type: 'torchvision.transforms.RandomRotation'
      args: [2]
    totensor:
      type: 'torchvision.transforms.ToTensor'

validation_data:
  type: 'Caltech256'
  kwargs:
    root: '~/data/caltech256/256_ObjectCategories'
    split: 'val'
  transformation:
    resize:
      type: 'torchvision.transforms.Resize'
      args: [256]
    crop:
      type: 'torchvision.transforms.CenterCrop'
      args: [224]
    totensor:
      type: 'torchvision.transforms.ToTensor'

architecture:
  type: 'AttackerModel'
  kwargs:
    p: 2
    eps: 3.0
    step_size: 0.5
    iterations: 0
    loss_name: 'nn.CrossEntropyLoss'
    use_best: True
    random_start: False
    data_mean: [0.485, 0.456, 0.406]
    data_std: [0.229, 0.224, 0.225]

  initialization:
    conv: 'kaiming'
    linear: 'kaiming'

  layers:
    conv1: 
      type: 'nn.Conv2d'
      args: [3, 64, 7]
      stride: 2
      padding: 3
      bias: False
    bn1:
      type: 'nn.BatchNorm2d'
      num_features: 64
    relu1:
      type: 'nn.ReLU'
      inplace: True
    pool1:
      type: 'nn.MaxPool2d'
      args: [3, 2, 1]

    stage1_1:
      type: 'ResNetBottleneck'
      inplanes: 64
      planes: 256
      stride: 1
    stage1_2:
      type: 'ResNetBottleneck'
      inplanes: 256
      planes: 256
      stride: 1
    stage1_3:
      type: 'ResNetBottleneck'
      inplanes: 256
      planes: 256
      stride: 1

    stage2_1:
      type: 'ResNetBottleneck'
      inplanes: 256
      planes: 512
      stride: 2
    stage2_2:
      type: 'ResNetBottleneck'
      inplanes: 512
      planes: 512
      stride: 1
    stage2_3:
      type: 'ResNetBottleneck'
      inplanes: 512
      planes: 512
      stride: 1
    stage2_4:
      type: 'ResNetBottleneck'
      inplanes: 512
      planes: 512
      stride: 1

    stage3_1:
      type: 'ResNetBottleneck'
      inplanes: 512
      planes: 1024
      stride: 2
    stage3_2:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 1024
      stride: 1
    stage3_3:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 1024
      stride: 1
    stage3_4:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 1024
      stride: 1
    stage3_5:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 1024
      stride: 1
    stage3_6:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 1024
      stride: 1


    stage4_1:
      type: 'ResNetBottleneck'
      inplanes: 1024
      planes: 2048
      stride: 2
    stage4_2:
      type: 'ResNetBottleneck'
      inplanes: 2048
      planes: 2048
      stride: 1
    stage4_3:
      type: 'ResNetBottleneck'
      inplanes: 2048
      planes: 2048
      stride: 1

    # print4:
    #   type: 'PrintOutputShape'
    avg_pool:
      type: 'nn.AdaptiveAvgPool2d'
      args: [1]
    flatten:
      type: 'Flatten'
      dim: 1
    fc1:
      type: 'nn.Linear'
      args: [2048, 2048]
    fc1_relu:
      type: 'nn.ReLU'
      inplace: True
    fc:
      type: 'nn.Linear'
      args: [2048, 257]

loss:
  nll:
    type: 'nn.CrossEntropyLoss'

metrics:
  cleanacc:
    type: 'Accuracy'
    topk: 1


evaluations:
  auto_attack_l2:
    type: 'AutoAttackDomainAccuracy'
    eval_freq: [15, 51, 76, 100]
    robust_logit_index: 
    batch_size: 100
    n_samples: 1000
    # attacks_to_run: ['apgd-ce', 'apgd-t']
    norm_p: 2
    data_mean: [0, 0, 0]
    data_std: [1, 1, 1]
    epsilons: [3.0]
    domains:
      all: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256]
     

training:
  epochs: 101
  batch_size: 128  # batch size for training
  
  sync_bn: True
  workers: 16  # data loader workers
  train_gpu: [0]

  print_freq: 10
  save_freq: 1
  save_path: exp/caltech256/transferred_from_imagenetA_instanceranking_weightedincreasing2to10/$MODELNAME/model

  pretrained_weights: exp/imagenet200/weightedincreasing2to10_esat_pgd7_increasing_entropy/resnet50_A9.PGDs0.5i7e3.0_B1.none/model/best_rob_acc.pth
  # resume: exp/cifar100/vanilla_pgd7/$MODELNAME/model/best_rob_acc.pth
  # evaluate_only: True 
  freeze_bn: True

  optimizer:
    type: 'SGD'
    lr: 0.1
    momentum: 0.9
    weight_decay: 1.e-4
    layers: ['fc1', 'fc']
  lrscheduler:
    type: 'MultiStepLR'
    gamma: 0.1
    milestones: [9550, 14325]  # total Caltech batches: 191
    

validate:
  batch_size: 1000 # batch size for validation during training, memory and speed tradeoff
  print_freq: 10
