manual_seed: 123

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

training_data:
  type: 'CIFAR10WithIndex'
  kwargs:
    root: '~/data/'
    train: True
  transformation:
    crop:
      type: 'torchvision.transforms.RandomCrop'
      args: [32, 4]  #size, padding
    flip: 
      type: 'torchvision.transforms.RandomHorizontalFlip'
    colorjitter:
      type: 'torchvision.transforms.ColorJitter'
      args: [.25, .25, .25]
    rotation:
      type: 'torchvision.transforms.RandomRotation'
      args: [2]
    totensor:
      type: 'torchvision.transforms.ToTensor'

validation_data:
  type: 'CIFAR10WithIndex'
  kwargs:
    root: '~/data/'
    train: False
  transformation:
    totensor:
      type: 'torchvision.transforms.ToTensor'

architecture:
  type: 'InstanceDomainAttackerModel'
  kwargs:
    ranking: {ranking_filep}
    attacked_domain1_bins: {A}
    bins: {nbins}
    p_domain1: 2
    eps_domain1: 0.5
    step_size_domain1: 0.1
    it_domain1: 7
    loss_name: 'nn.CrossEntropyLoss'
    use_best: True
    random_start: False
    data_mean: [0.4914, 0.4822, 0.4465]
    data_std: [0.2023, 0.1994, 0.2010]

  initialization:
    conv: 'kaiming'
    linear: 'kaiming'

  layers:
    wrn70_16: 
      type: 'WideResNet'
      num_classes: 10
      depth: 70
      width: 16

loss:
  nll:
    type: 'nn.CrossEntropyLoss'

metrics:
  cleanacc:
    type: 'Accuracy'
    topk: 1
  domainA_acc:
    type: 'InstanceDomainAccuracy'
    domain_cfg: 
      ranking: {ranking_filep}
      domain: {A}
      bins: {nbins}
  domainB_acc:
    type: 'InstanceDomainAccuracy'
    domain_cfg: 
      ranking: {ranking_filep}
      domain: {B}
      bins: {nbins}

evaluations:
  auto_attack_l2:
    type: 'AutoAttackDomainAccuracy'
    eval_freq: [15, 50, 101, 151, 200]
    robust_logit_index: 
    batch_size: 1000
    n_samples: 1000
    attacks_to_run: ['apgd-ce', 'apgd-t']
    norm_p: 2
    data_mean: [0, 0, 0]
    data_std: [1, 1, 1]
    epsilons: [0.5]
    domains:
      all: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      class0: [0]
      class1: [1]
      class2: [2]
      class3: [3]
      class4: [4]
      class5: [5]
      class6: [6]
      class7: [7]
      class8: [8]
      class9: [9]
      

training:
  epochs: 201
  batch_size: 128  # batch size for training
  
  sync_bn: True
  workers: 4  # data loader workers
  train_gpu: [0]

  print_freq: 100
  save_freq: 1
  save_path: exp/cifar10/wrn70-16_esat_pgd7_decreasing_entropy/$MODELNAME/model

  # resume: exp/cifar10/wrn70-16_esat_pgd7_decreasing_entropy/$MODELNAME/model/train_epoch_49.pth
  # evaluate_only: True 

  mixed_precision:
    opt_level: 'O1'

  optimizer:
    type: 'SGD'
    lr: 0.1
    momentum: 0.9
    weight_decay: 5.e-4
  lrscheduler:
    type: 'MultiStepLR'
    gamma: 0.1
    milestones: [39000, 58500]
    

validate:
  batch_size: 1000 # batch size for validation during training, memory and speed tradeoff
  print_freq: 10
